import { convertLevel } from "./level-converter.js";
import type { LevelDefinition } from "./types.js";

const testLevels: LevelDefinition[] = [
  convertLevel({
    availableComponents: ["server"],
    cacheHitRate: 0,
    coachMessages: [],
    componentUnlocks: [],
    feedbackText: ["Feedback A"],
    id: "test-level-a",
    lockedNodeIds: [],
    monthlyBudget: 100,
    objectiveText: "Objective A",
    solutions: [{ edges: [], nodes: [] }],
    startingEdges: [],
    startingNodes: [{ componentType: "users", id: "users-1", position: { x: 0, y: 0 } }],
    timeout: 60000,
    title: "Level A",
    trafficPeak: 0.01,
    trafficStart: 0.01,
    trafficTarget: 0.01,
    winSustainMs: 3000,
  }),
  convertLevel({
    availableComponents: ["server", "server-large"],
    cacheHitRate: 0,
    coachMessages: [],
    componentUnlocks: [],
    feedbackText: ["Feedback B"],
    id: "test-level-b",
    lockedNodeIds: [],
    monthlyBudget: 200,
    objectiveText: "Objective B",
    solutions: [{ edges: [], nodes: [] }],
    startingEdges: [],
    startingNodes: [{ componentType: "users", id: "users-1", position: { x: 0, y: 0 } }],
    timeout: 60_000,
    title: "Level B",
    trafficPeak: 0.02,
    trafficStart: 0.02,
    trafficTarget: 0.02,
    winSustainMs: 3_000,
  }),
  convertLevel({
    availableComponents: ["server", "server-large", "db"],
    cacheHitRate: 0,
    coachMessages: [],
    componentUnlocks: [],
    feedbackText: ["Feedback C"],
    id: "test-level-c",
    lockedNodeIds: [],
    monthlyBudget: 300,
    objectiveText: "Objective C",
    solutions: [{ edges: [], nodes: [] }],
    startingEdges: [],
    startingNodes: [{ componentType: "users", id: "users-1", position: { x: 0, y: 0 } }],
    timeout: 60_000,
    title: "Level C",
    trafficPeak: 0.03,
    trafficStart: 0.03,
    trafficTarget: 0.03,
    winSustainMs: 3_000,
  }),
];

const levelWithTimedCoachMessage: LevelDefinition = convertLevel({
  availableComponents: ["server"],
  cacheHitRate: 0,
  coachMessages: [{ atMs: 2_000, text: "Database is the bottleneck — upgrade it." }],
  componentUnlocks: [],
  feedbackText: [],
  id: "test-level-coach",
  lockedNodeIds: [],
  monthlyBudget: 9_999,
  objectiveText: "Objective Coach",
  solutions: [{ edges: [], nodes: [] }],
  startingEdges: [],
  startingNodes: [{ componentType: "users", id: "users-1", position: { x: 0, y: 0 } }],
  timeout: 60_000,
  title: "Level Coach",
  trafficPeak: 0.01,
  trafficStart: 0.01,
  trafficTarget: 0.01,
  winSustainMs: 3_000,
});

export { levelWithTimedCoachMessage, testLevels };
