import type { LevelDefinition } from "./types.js";

const testLevels: LevelDefinition[] = [
  {
    availableComponents: ["server"],
    cacheHitRate: 0,
    coachMessages: [],
    componentUnlocks: [],
    feedbackText: ["Feedback A"],
    id: "test-level-a",
    lockedNodeIds: [],
    monthlyBudget: 100,
    objectiveText: "Objective A",
    startingEdges: [],
    startingNodes: [{ componentType: "users", id: "users-1", position: { x: 0, y: 0 } }],
    timeout: 60,
    title: "Level A",
    trafficPeak: 10,
    trafficStart: 10,
    trafficTarget: 10,
    winSustainSeconds: 3,
  },
  {
    availableComponents: ["server", "server-large"],
    cacheHitRate: 0,
    coachMessages: [],
    componentUnlocks: [],
    feedbackText: ["Feedback B"],
    id: "test-level-b",
    lockedNodeIds: [],
    monthlyBudget: 200,
    objectiveText: "Objective B",
    startingEdges: [],
    startingNodes: [{ componentType: "users", id: "users-1", position: { x: 0, y: 0 } }],
    timeout: 60,
    title: "Level B",
    trafficPeak: 20,
    trafficStart: 20,
    trafficTarget: 20,
    winSustainSeconds: 3,
  },
  {
    availableComponents: ["server", "server-large", "db"],
    cacheHitRate: 0,
    coachMessages: [],
    componentUnlocks: [],
    feedbackText: ["Feedback C"],
    id: "test-level-c",
    lockedNodeIds: [],
    monthlyBudget: 300,
    objectiveText: "Objective C",
    startingEdges: [],
    startingNodes: [{ componentType: "users", id: "users-1", position: { x: 0, y: 0 } }],
    timeout: 60,
    title: "Level C",
    trafficPeak: 30,
    trafficStart: 30,
    trafficTarget: 30,
    winSustainSeconds: 3,
  },
];

export { testLevels };
